#!/usr/bin/env node
// netlify/migrate.js — runs during Netlify build (node migrate.js)
// Creates all required Supabase tables using service role key

const SB_URL = process.env.SUPABASE_URL;
const SB_KEY = process.env.SUPABASE_SERVICE_KEY || process.env.SUPABASE_ANON_KEY;

if (!SB_URL || !SB_KEY) {
  console.log('[migrate] Supabase not configured — skipping');
  process.exit(0);
}

const TABLES = [
  // Notification settings (existing)
  `CREATE TABLE IF NOT EXISTS notification_settings (
    id             BIGSERIAL PRIMARY KEY,
    user_id        TEXT NOT NULL UNIQUE,
    email          TEXT,
    ch_email_on    BOOLEAN DEFAULT FALSE,
    ch_email_val   TEXT DEFAULT '',
    ch_whatsapp_on BOOLEAN DEFAULT FALSE,
    ch_whatsapp_val TEXT DEFAULT '',
    ch_telegram_on BOOLEAN DEFAULT FALSE,
    ch_telegram_val TEXT DEFAULT '',
    ch_push_on     BOOLEAN DEFAULT FALSE,
    timing         TEXT DEFAULT 'immediate',
    updated_at     TIMESTAMPTZ DEFAULT NOW()
  )`,

  // Subscribers / paying users
  `CREATE TABLE IF NOT EXISTS t365_subscribers (
    id           BIGSERIAL PRIMARY KEY,
    email        TEXT NOT NULL UNIQUE,
    full_name    TEXT DEFAULT '',
    plan         TEXT NOT NULL DEFAULT 'scout',
    status       TEXT NOT NULL DEFAULT 'active',
    billing      TEXT DEFAULT 'monthly',
    ls_order_id  TEXT,
    trial_ends   TIMESTAMPTZ,
    created_at   TIMESTAMPTZ DEFAULT NOW(),
    updated_at   TIMESTAMPTZ DEFAULT NOW()
  )`,

  // Players from API-Football
  `CREATE TABLE IF NOT EXISTS t365_players (
    id           BIGSERIAL PRIMARY KEY,
    player_id    INTEGER NOT NULL,
    name         TEXT NOT NULL,
    firstname    TEXT, lastname TEXT,
    age          INTEGER, nationality TEXT, photo TEXT,
    position     TEXT, team_id INTEGER, team_name TEXT,
    games_played INTEGER DEFAULT 0,
    goals        INTEGER DEFAULT 0,
    assists      INTEGER DEFAULT 0,
    rating       NUMERIC(4,2) DEFAULT 0,
    minutes      INTEGER DEFAULT 0,
    contract_end DATE, market_value NUMERIC(12,2),
    league_id    INTEGER NOT NULL DEFAULT 271,
    season       INTEGER NOT NULL DEFAULT 2025,
    updated_at   TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(player_id, league_id, season)
  )`,

  // Injuries
  `CREATE TABLE IF NOT EXISTS t365_injuries (
    id           BIGSERIAL PRIMARY KEY,
    player_id    INTEGER NOT NULL,
    player_name  TEXT, team_name TEXT,
    injury_type  TEXT, reason TEXT,
    league_id    INTEGER DEFAULT 271,
    season       INTEGER DEFAULT 2025,
    updated_at   TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(player_id, season, injury_type)
  )`,

  // Alerts generated by scan-alerts
  `CREATE TABLE IF NOT EXISTS t365_alerts (
    id           BIGSERIAL PRIMARY KEY,
    type         TEXT NOT NULL,
    player_id    INTEGER, player_name TEXT, team_name TEXT,
    title        TEXT NOT NULL, body TEXT,
    urgency      TEXT DEFAULT 'medium',
    is_read      BOOLEAN DEFAULT FALSE,
    created_at   TIMESTAMPTZ DEFAULT NOW()
  )`,

  // Indexes
  `CREATE INDEX IF NOT EXISTS idx_subscribers_email  ON t365_subscribers(email)`,
  `CREATE INDEX IF NOT EXISTS idx_subscribers_plan   ON t365_subscribers(plan)`,
  `CREATE INDEX IF NOT EXISTS idx_players_league     ON t365_players(league_id, season)`,
  `CREATE INDEX IF NOT EXISTS idx_alerts_urgency     ON t365_alerts(urgency, created_at)`,
];

async function run() {
  console.log('[migrate] Starting Supabase migration...');
  let ok = 0, skip = 0;

  for (const sql of TABLES) {
    const name = sql.trim().slice(0, 60).replace(/\s+/g,' ');
    try {
      // Use Supabase SQL endpoint (requires service role)
      const r = await fetch(`${SB_URL}/rest/v1/rpc/exec_sql`, {
        method: 'POST',
        headers: {
          'apikey': SB_KEY,
          'Authorization': `Bearer ${SB_KEY}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ sql }),
      });

      if (r.ok) {
        console.log(`[migrate] ✅ ${name}`);
        ok++;
      } else {
        const err = await r.text();
        if (err.includes('already exists')) {
          console.log(`[migrate] ⏭  already exists: ${name}`);
          skip++;
        } else {
          console.log(`[migrate] ⚠️  ${r.status}: ${err.slice(0,100)}`);
          skip++;
        }
      }
    } catch(e) {
      console.log(`[migrate] ⚠️  ${name}: ${e.message.slice(0,80)}`);
      skip++;
    }
  }

  console.log(`[migrate] Done: ${ok} created, ${skip} skipped`);
}

run().catch(e => { console.error('[migrate] Fatal:', e.message); process.exit(0); });
